@extends('layouts.app')

@section('styles')
    <link rel="stylesheet" href="{{ asset('css/report.css') }}">
@endsection
@section('content')

<div class="reports-page">

    {{-- Header --}}
    <div class="reports-header">

        <div>

            <h1>Profit Report</h1>

            <p>
                Analyze revenue, product costs and gross profit.
            </p>

        </div>

    </div>


    {{-- Date Filter --}}
    <div class="report-filter-card">

        <form method="GET" action="{{ route('reports.profit') }}">

            <div class="filter-group">

                <div class="filter-field">

                    <label for="from_date">
                        From Date
                    </label>

                    <input
                        type="date"
                        name="from_date"
                        id="from_date"
                        value="{{ request('from_date') }}"
                    >

                </div>


                <div class="filter-field">

                    <label for="to_date">
                        To Date
                    </label>

                    <input
                        type="date"
                        name="to_date"
                        id="to_date"
                        value="{{ request('to_date') }}"
                    >

                </div>


                <div class="filter-actions">

                    <button
                        type="submit"
                        class="btn-report-filter"
                    >
                        <i class="fa-solid fa-filter"></i>
                        Apply Filter
                    </button>


                    <a
                        href="{{ route('reports.profit') }}"
                        class="btn-report-reset"
                    >
                        <i class="fa-solid fa-rotate-left"></i>
                        Reset
                    </a>

                </div>

            </div>

        </form>

    </div>


    {{-- Profit Summary --}}
    <div class="report-summary-grid">


        {{-- Revenue --}}
        <div class="report-summary-card">

            <div class="summary-icon">

                <i class="fa-solid fa-indian-rupee-sign"></i>

            </div>

            <div>

                <span>Sales Revenue</span>

                <h2>
                    ₹{{ number_format($totalRevenue, 2) }}
                </h2>

            </div>

        </div>


        {{-- Cost --}}
        <div class="report-summary-card">

            <div class="summary-icon">

                <i class="fa-solid fa-box"></i>

            </div>

            <div>

                <span>Cost of Goods Sold</span>

                <h2>
                    ₹{{ number_format($totalCost, 2) }}
                </h2>

            </div>

        </div>


        {{-- Profit --}}
        <div class="report-summary-card">

            <div class="summary-icon">

                <i class="fa-solid fa-chart-line"></i>

            </div>

            <div>

                <span>Gross Profit</span>

                <h2>
                    ₹{{ number_format($grossProfit, 2) }}
                </h2>

            </div>

        </div>


        {{-- Margin --}}
        <div class="report-summary-card">

            <div class="summary-icon">

                <i class="fa-solid fa-percent"></i>

            </div>

            <div>

                <span>Profit Margin</span>

                <h2>
                    {{ number_format($profitMargin, 2) }}%
                </h2>

            </div>

        </div>

    </div>


    {{-- Formula --}}
    <div class="profit-formula-card">

        <div class="profit-formula-icon">

            <i class="fa-solid fa-calculator"></i>

        </div>

        <div>

            <strong>Gross Profit Calculation</strong>

            <p>

                ₹{{ number_format($totalRevenue, 2) }}

                −

                ₹{{ number_format($totalCost, 2) }}

                =

                <strong>
                    ₹{{ number_format($grossProfit, 2) }}
                </strong>

            </p>

        </div>

    </div>


    {{-- Product Profit Table --}}
    <div class="report-section">

        <div class="report-section-header">

            <div>

                <h2>Product-wise Profit</h2>

                <p>
                    Profit generated by each sold product.
                </p>

            </div>


            <span class="report-count">

                {{ $productProfits->total() }} Products

            </span>

        </div>


        <div class="report-table-wrapper">

            <table class="report-table">

                <thead>

                    <tr>

                        <th>#</th>

                        <th>Product</th>

                        <th>SKU</th>

                        <th>Qty Sold</th>

                        <th>Revenue</th>

                        <th>Cost</th>

                        <th>Profit</th>

                    </tr>

                </thead>


                <tbody>

                    @forelse($productProfits as $index => $product)

                        <tr>

                            <td>
                                {{ $productProfits->firstItem() + $index }}
                            </td>


                            <td>

                                <strong>
                                    {{ $product->name }}
                                </strong>

                            </td>


                            <td>

                                <span class="product-sku">
                                    {{ $product->sku }}
                                </span>

                            </td>


                            <td>

                                <span class="quantity-badge">
                                    {{ number_format($product->quantity_sold) }}
                                </span>

                            </td>


                            <td>

                                ₹{{ number_format(
                                    $product->revenue,
                                    2
                                ) }}

                            </td>


                            <td>

                                ₹{{ number_format(
                                    $product->cost,
                                    2
                                ) }}

                            </td>


                            <td>

                                <strong
                                    class="{{ $product->profit >= 0
                                        ? 'profit-positive'
                                        : 'profit-negative'
                                    }}"
                                >

                                    ₹{{ number_format(
                                        $product->profit,
                                        2
                                    ) }}

                                </strong>

                            </td>

                        </tr>

                    @empty

                        <tr>

                            <td colspan="7">

                                <div class="empty-table">

                                    <i class="fa-solid fa-chart-line"></i>

                                    <h3>
                                        No profit data found
                                    </h3>

                                    <p>
                                        There are no completed sales
                                        for the selected period.
                                    </p>

                                </div>

                            </td>

                        </tr>

                    @endforelse

                </tbody>

            </table>

        </div>


        @if($productProfits->hasPages())

            <div class="report-pagination">

                {{ $productProfits->links() }}

            </div>

        @endif

    </div>

</div>

@endsection